"""
Codigo para criar uma tabela de exemplo no banco Oracle de HML.

Author: Gustavo F. Lima
License: MIT
Created: 2025
"""

import os
import oracledb
from dotenv import load_dotenv


def init_oracle():
    """
    Inicializa o Oracle Client apenas se necessário
    """
    # Instalar o oracle cliente e incluir na path: C:\oracle\instantclient_23_9
    if os.name == "nt":  # Windows
        lib_dir = r"C:\oracle\instantclient_23_9"
    else:  # Linux / Docker
        lib_dir = "/opt/oracle/instantclient_23_26"

    oracledb.init_oracle_client(lib_dir=lib_dir)


def get_connection():
    load_dotenv()

    init_oracle()

    user = os.getenv("DW_C5DBSTDY_CONSINCO_HML_USER")
    pwd = os.getenv("DW_C5DBSTDY_CONSINCO_HML_PWD")
    host = os.getenv("DW_C5DBSTDY_CONSINCO_HML_HOST")
    port = os.getenv("DW_C5DBSTDY_CONSINCO_HML_PORT")
    service = os.getenv("DW_C5DBSTDY_CONSINCO_HML_SERVICE")

    dsn = f"{host}:{port}/{service}"

    return oracledb.connect(
        user=user,
        password=pwd,
        dsn=dsn
    )



def create_example_table():
    connection = get_connection()

    try:
        with connection.cursor() as cursor:
            cursor.execute("ALTER SESSION SET CURRENT_SCHEMA = DW")

            cursor.execute("""
                CREATE TABLE DW.EXEMPLO_TABELA (
                    ID            NUMBER GENERATED BY DEFAULT AS IDENTITY,
                    NOME          VARCHAR2(100) NOT NULL,
                    DESCRICAO     VARCHAR2(255),
                    DATA_CRIACAO  DATE DEFAULT SYSDATE,
                    CONSTRAINT PK_EXEMPLO_TABELA PRIMARY KEY (ID)
                )
            """)

            print("✅ Tabela DW.EXEMPLO_TABELA criada com sucesso!")

        connection.commit()

    except oracledb.DatabaseError as e:
        error, = e.args
        print("❌ Erro Oracle:", error.message)

    finally:
        connection.close()


if __name__ == "__main__":
    create_example_table()


# Na .env que fica na raiz do repo, incluir as credenciais:

# DW_C5DBSTDY_CONSINCO_HML_USER=OWNER
# DW_C5DBSTDY_CONSINCO_HML_PWD="SENHA"
# DW_C5DBSTDY_CONSINCO_HML_HOST=HOST
# DW_C5DBSTDY_CONSINCO_HML_PORT=PORT
# DW_C5DBSTDY_CONSINCO_HML_SERVICE=BANCO